name: Check release condition
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'release')
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Dump version
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        id: release
        run: |
          echo "$PR_TITLE" | grep -E "^release:? v[0-9]+(\.[0-9]+)*$" || exit 1
          VERSION=$(echo "$PR_TITLE" | sed -nE 's/^release:? (v[0-9]+(\.[0-9]+)*)$/\1/p')
          echo "$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Dump poetry version
        id: poetry
        run: |
          VERSION=$(grep version pyproject.toml | sed -E 's/.* "([0-9\-\.]*)"/v\1/g')
          echo "$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Check version
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.version }}
          POETRY_VERSION: ${{ steps.poetry.outputs.version }}
        run: |
          if [[ "$RELEASE_VERSION" == "$POETRY_VERSION" ]]; then
            echo "VERSION MATCH"
          else
            echo "VERSION MISMATCH"
            exit 1
          fi
      - name: Check CHANGELOG
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.version }}
        run: |
          if ! grep -Fq "$RELEASE_VERSION" CHANGELOG.md; then
            echo "VERSION NOT FOUND IN CHANGELOG"
            exit 1
          fi
